import { CoffeeShop, Branch, Category, Product, Coupon } from "../types";

export const initialCoffeeShops: CoffeeShop[] = [
  {
    id: "shop-lamiz",
    name: "Lamiz Coffee Roasters",
    nameFa: "کافه لمیز (تخصصی و روستری)",
    slug: "lamiz",
    logoUrl: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=300&auto=format&fit=crop&q=80",
    coverUrl: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=1200&auto=format&fit=crop&q=80",
    description: "Specialty coffee roastery offering freshly roasted single origin beans and artisan espresso blends.",
    descriptionFa: "روستری و زنجیره کافه‌های تخصصی؛ عرضه دانه‌های تازه برشته‌شده و نوشیدنی‌های دست‌ساز با بالاترین کیفیت.",
    phone: "۰۲۱-۲۲۷۴۵۶۰۰",
    themeColor: "#c2410c", // Amber-orange/Rust
    currency: "تومان",
    active: true,
    createdAt: new Date().toISOString(),
    instagram: "@lamizcoffee",
  },
  {
    id: "shop-buona",
    name: "Buona Specialty Coffee",
    nameFa: "کافه بونا (اسپشیالتی)",
    slug: "buona",
    logoUrl: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=300&auto=format&fit=crop&q=80",
    coverUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1200&auto=format&fit=crop&q=80",
    description: "Third-wave micro-roaster focusing on ethical sourcing, pour-overs, and delightful breakfast.",
    descriptionFa: "کافه موج سوم با تمرکز بر دم‌آوری‌های تخصصی نسل جدید، ماچای اصیل ژاپنی و شیرینی‌های تازه فرانسوی.",
    phone: "۰۲۱-۸۸۹۹۲۲۰۱",
    themeColor: "#0f766e", // Teal
    currency: "تومان",
    active: true,
    createdAt: new Date().toISOString(),
    instagram: "@buonacoffee",
  },
];

export const initialBranches: Branch[] = [
  // Lamiz Branches
  {
    id: "branch-lamiz-tajrish",
    coffeeShopId: "shop-lamiz",
    name: "Tajrish Branch",
    nameFa: "شعبه تجریش (میدان قدس)",
    address: "Tajrish Sq, Next to Cinema Astara",
    addressFa: "تهران، میدان تجریش، ابتدای خیابان باهنر، پلاک ۱۲",
    phone: "۰۲۱-۲۲۷۱۰۰۲۱",
    coordinates: { lat: 35.8078, lng: 51.4285 },
    openingHours: "۷:۳۰ صبح الی ۲۳:۳۰ شب",
    deliveryRadiusKm: 6.5,
    minOrderAmount: 80000,
    deliveryFee: 30000,
    pickupAvailable: true,
    deliveryAvailable: true,
    active: true,
  },
  {
    id: "branch-lamiz-saadatabad",
    coffeeShopId: "shop-lamiz",
    name: "Saadat Abad Branch",
    nameFa: "شعبه سعادت‌آباد (میدان کاج)",
    address: "Saadat Abad, Kaj Sq, Sarv Sharghi St",
    addressFa: "تهران، سعادت‌آباد، نرسیده به میدان کاج، نبش خیابان نهم",
    phone: "۰۲۱-۲۲۰۸۹۴۱۱",
    coordinates: { lat: 35.7794, lng: 51.3752 },
    openingHours: "۸:۰۰ صبح الی ۲۴:۰۰ شب",
    deliveryRadiusKm: 7.0,
    minOrderAmount: 100000,
    deliveryFee: 28000,
    pickupAvailable: true,
    deliveryAvailable: true,
    active: true,
  },
  {
    id: "branch-lamiz-vanak",
    coffeeShopId: "shop-lamiz",
    name: "Vanak Branch",
    nameFa: "شعبه ونک (ملاصدرا)",
    address: "Mollasadra Ave, Corner of Shiraz St",
    addressFa: "تهران، میدان ونک، خیابان ملاصدرا، نرسیده به شیراز، پلاک ۴۵",
    phone: "۰۲۱-۸۸۰۳۱۴۵۲",
    coordinates: { lat: 35.7592, lng: 51.4011 },
    openingHours: "۷:۳۰ صبح الی ۲۳:۰۰ شب",
    deliveryRadiusKm: 5.0,
    minOrderAmount: 80000,
    deliveryFee: 25000,
    pickupAvailable: true,
    deliveryAvailable: true,
    active: true,
  },
  // Buona Branches
  {
    id: "branch-buona-central",
    coffeeShopId: "shop-buona",
    name: "Central Roastery Branch",
    nameFa: "شعبه مرکزی (کریم‌خان)",
    address: "Karimkhan Ave, Iranshahr St",
    addressFa: "تهران، خیابان کریم‌خان زند، خیابان ایرانشهر، پلاک ۷۸",
    phone: "۰۲۱-۸۸۳۰۷۵۴۰",
    coordinates: { lat: 35.7145, lng: 51.4187 },
    openingHours: "۸:۰۰ صبح الی ۲۳:۰۰ شب",
    deliveryRadiusKm: 6.0,
    minOrderAmount: 90000,
    deliveryFee: 25000,
    pickupAvailable: true,
    deliveryAvailable: true,
    active: true,
  },
];

export const initialCategories: Category[] = [
  {
    id: "cat-hot-coffee",
    coffeeShopId: "shop-lamiz",
    name: "Hot Coffee",
    nameFa: "قهوه گرم",
    icon: "Coffee",
    sortOrder: 1,
    active: true,
  },
  {
    id: "cat-cold-coffee",
    coffeeShopId: "shop-lamiz",
    name: "Cold Coffee",
    nameFa: "قهوه سرد",
    icon: "CupSoda",
    sortOrder: 2,
    active: true,
  },
  {
    id: "cat-cold-drinks",
    coffeeShopId: "shop-lamiz",
    name: "Cold Drinks",
    nameFa: "نوشیدنی سرد",
    icon: "GlassWater",
    sortOrder: 3,
    active: true,
  },
  {
    id: "cat-tea",
    coffeeShopId: "shop-lamiz",
    name: "Tea & Infusions",
    nameFa: "چای و دمنوش",
    icon: "Flower2",
    sortOrder: 4,
    active: true,
  },
  {
    id: "cat-dessert",
    coffeeShopId: "shop-lamiz",
    name: "Dessert",
    nameFa: "دسر",
    icon: "IceCream",
    sortOrder: 5,
    active: true,
  },
  {
    id: "cat-cake",
    coffeeShopId: "shop-lamiz",
    name: "Cakes & Pastries",
    nameFa: "کیک و شیرینی",
    icon: "CakeSlice",
    sortOrder: 6,
    active: true,
  },
  {
    id: "cat-breakfast",
    coffeeShopId: "shop-lamiz",
    name: "Breakfast",
    nameFa: "صبحانه",
    icon: "Utensils",
    sortOrder: 7,
    active: true,
  },
  {
    id: "cat-snacks",
    coffeeShopId: "shop-lamiz",
    name: "Warm Snacks",
    nameFa: "میان‌وعده",
    icon: "Sandwich",
    sortOrder: 8,
    active: true,
  },
];

// Standard Coffee Modifier Groups
export const standardCoffeeModifiers = [
  {
    id: "mod-size",
    name: "Size",
    nameFa: "اندازه فنجان",
    required: true,
    minSelect: 1,
    maxSelect: 1,
    options: [
      { id: "size-s", name: "Standard (Single)", nameFa: "استاندارد (تک شات)", priceDelta: 0, isDefault: true },
      { id: "size-m", name: "Medium (Double)", nameFa: "متوسط (دو شات)", priceDelta: 18000 },
      { id: "size-l", name: "Large (Triple)", nameFa: "بزرگ (سه شات)", priceDelta: 32000 },
    ],
  },
  {
    id: "mod-milk",
    name: "Milk Type",
    nameFa: "نوع شیر",
    required: false,
    minSelect: 0,
    maxSelect: 1,
    options: [
      { id: "milk-regular", name: "Whole Milk", nameFa: "شیر پرچرب معمولی", priceDelta: 0, isDefault: true },
      { id: "milk-lowfat", name: "Low Fat", nameFa: "شیر کم‌چرب", priceDelta: 0 },
      { id: "milk-oat", name: "Oat Milk (Barista)", nameFa: "شیر جو دوسر گیاهی (Oat)", priceDelta: 24000 },
      { id: "milk-almond", name: "Almond Milk", nameFa: "شیر بادام ارگانیک", priceDelta: 28000 },
    ],
  },
  {
    id: "mod-sugar",
    name: "Sugar / Sweetness",
    nameFa: "میزان شیرینی",
    required: false,
    minSelect: 0,
    maxSelect: 1,
    options: [
      { id: "sugar-none", name: "Unsweetened (0%)", nameFa: "بدون شکر (طبیعی)", priceDelta: 0, isDefault: true },
      { id: "sugar-low", name: "Light Sugar (30%)", nameFa: "کم‌شیرین", priceDelta: 0 },
      { id: "sugar-normal", name: "Normal (100%)", nameFa: "شیرینی استاندارد", priceDelta: 0 },
      { id: "sugar-syrup", name: "Brown Cane Sugar", nameFa: "شکر قهوه‌ای طبیعی", priceDelta: 6000 },
    ],
  },
  {
    id: "mod-extras",
    name: "Extras & Syrups",
    nameFa: "افزودنی‌های اختیاری",
    required: false,
    minSelect: 0,
    maxSelect: 3,
    options: [
      { id: "ext-shot", name: "Extra Espresso Shot", nameFa: "یک شات اسپرسو اضافه", priceDelta: 22000 },
      { id: "ext-vanilla", name: "Madagascar Vanilla Syrup", nameFa: "سیروپ وانیل ماداگاسکار", priceDelta: 16000 },
      { id: "ext-caramel", name: "Salted Caramel Sauce", nameFa: "سس کارامل نمکی دست‌ساز", priceDelta: 18000 },
      { id: "ext-whipped", name: "Fresh Whipped Cream", nameFa: "خامه زده‌شده تازه", priceDelta: 15000 },
    ],
  },
];

export const coldCoffeeModifiers = [
  ...standardCoffeeModifiers,
  {
    id: "mod-ice",
    name: "Ice Level",
    nameFa: "میزان یخ",
    required: false,
    minSelect: 0,
    maxSelect: 1,
    options: [
      { id: "ice-regular", name: "Standard Ice", nameFa: "یخ استاندارد", priceDelta: 0, isDefault: true },
      { id: "ice-less", name: "Less Ice", nameFa: "کم‌یخ", priceDelta: 0 },
      { id: "ice-extra", name: "Extra Ice", nameFa: "پریخ و خنک", priceDelta: 0 },
    ],
  },
];

export const initialProducts: Product[] = [
  // HOT COFFEES
  {
    id: "prod-latte-artisan",
    coffeeShopId: "shop-lamiz",
    categoryId: "cat-hot-coffee",
    name: "Artisan Cafe Latte",
    nameFa: "کافه لاته دست‌ساز",
    description: "Double shot of rich specialty espresso with velvety steamed milk and fine micro-foam art.",
    descriptionFa: "دو شات اسپرسوی تخصصی با ترکیب شیر بخاردیده مخملی و آرت باریستایی دلنشین.",
    image: "https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?w=600&auto=format&fit=crop&q=80",
    basePrice: 95000,
    compareAtPrice: 110000,
    active: true,
    available: true,
    featured: true,
    popular: true,
    preparationTime: 5,
    ingredients: ["دانه ۱۰۰٪ عربیکا کلمبیا", "شیر تازه پاستوریزه", "فوم کرمی"],
    allergens: ["شیر و لاکتوز (قابل جایگزینی با گیاهی)"],
    calories: 165,
    tags: ["پرفروش", "اسپشیالتی", "کرم دار"],
    sortOrder: 1,
    modifierGroups: standardCoffeeModifiers,
  },
  {
    id: "prod-cappuccino-classic",
    coffeeShopId: "shop-lamiz",
    categoryId: "cat-hot-coffee",
    name: "Classic Cappuccino",
    nameFa: "کاپوچینو کلاسیک ایتالیایی",
    description: "Equal balance of bold espresso, silky steamed milk, and a thick cloud of foam dusted with cocoa.",
    descriptionFa: "تعادل کلاسیک یک‌سوم اسپرسوی غلیظ، یک‌سوم شیر داغ و یک‌سوم فوم متراکم با پودر دارچین یا کاکائو.",
    image: "https://images.unsplash.com/photo-1534778101976-62847782c213?w=600&auto=format&fit=crop&q=80",
    basePrice: 90000,
    active: true,
    available: true,
    featured: false,
    popular: true,
    preparationTime: 5,
    ingredients: ["اسپرسو رست متوسط", "فوم شیر غلیظ", "پودر کاکائو بلژیکی"],
    calories: 140,
    tags: ["کلاسیک", "صبحگاهی"],
    sortOrder: 2,
    modifierGroups: standardCoffeeModifiers,
  },
  {
    id: "prod-flat-white",
    coffeeShopId: "shop-lamiz",
    categoryId: "cat-hot-coffee",
    name: "Specialty Flat White",
    nameFa: "فلت وایت تخصصی",
    description: "Double ristretto shot with thin velvety microfoam for an intense coffee-forward flavor profile.",
    descriptionFa: "دو شات ریسترتوی غلیظ اتیوپی یرگاچف با لایه نازک میکروفوم برای عاشقان طعم قوی قهوه.",
    image: "https://images.unsplash.com/photo-1577968897966-3d4325b36b61?w=600&auto=format&fit=crop&q=80",
    basePrice: 98000,
    active: true,
    available: true,
    featured: true,
    popular: true,
    isNew: true,
    preparationTime: 4,
    ingredients: ["دابل ریسترتو اتیوپی", "میکروفوم شیر"],
    calories: 120,
    tags: ["قوی", "اسپشیالتی"],
    sortOrder: 3,
    modifierGroups: standardCoffeeModifiers,
  },
  {
    id: "prod-caramel-macchiato",
    coffeeShopId: "shop-lamiz",
    categoryId: "cat-hot-coffee",
    name: "Salted Caramel Macchiato",
    nameFa: "کارامل ماکیاتو نمکی",
    description: "Fresh vanilla-infused milk marked with double espresso and crosshatched with artisan caramel drizzle.",
    descriptionFa: "شیر وانیلی بخاردیده با شات اسپرسوی غلیظ و خطوط کارامل نمکی داغ دست‌ساز.",
    image: "https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=600&auto=format&fit=crop&q=80",
    basePrice: 115000,
    compareAtPrice: 130000,
    active: true,
    available: true,
    featured: true,
    popular: true,
    preparationTime: 6,
    ingredients: ["سیروپ وانیل ماداگاسکار", "اسپرسو دابل", "شیر", "سس کارامل نمکی"],
    calories: 240,
    tags: ["شیرین", "محبوب"],
    sortOrder: 4,
    modifierGroups: standardCoffeeModifiers,
  },
  {
    id: "prod-americano-v60",
    coffeeShopId: "shop-lamiz",
    categoryId: "cat-hot-coffee",
    name: "Americano Single Origin",
    nameFa: "آمریکانو کلمبیا سوپریمو",
    description: "Rich double espresso poured over hot purified water with notes of dark chocolate and orange peel.",
    descriptionFa: "دو شات اسپرسوی تازه روست‌شده بر بستر آب تصفیه‌شده داغ با نت‌های شکلات تلخ و مرکبات.",
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80",
    basePrice: 75000,
    active: true,
    available: true,
    featured: false,
    popular: false,
    preparationTime: 3,
    ingredients: ["اسپرسو دابل عربیکا", "آب گرم تصفیه شده"],
    calories: 5,
    tags: ["کم‌کالری", "بدون‌شیر"],
    sortOrder: 5,
    modifierGroups: standardCoffeeModifiers,
  },

  // COLD COFFEES
  {
    id: "prod-iced-spanish-latte",
    coffeeShopId: "shop-lamiz",
    categoryId: "cat-cold-coffee",
    name: "Iced Spanish Latte",
    nameFa: "اسپنیش لاته سرد (آیسد)",
    description: "Condensed milk sweetness layered with cold fresh milk, slow-poured espresso, and crisp ice.",
    descriptionFa: "ترکیب شیر عسلی مخصوص با شیر خنک، دابل اسپرسوی پرمایه و تکه‌های یخ بلوری.",
    image: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=600&auto=format&fit=crop&q=80",
    basePrice: 110000,
    compareAtPrice: 125000,
    active: true,
    available: true,
    featured: true,
    popular: true,
    preparationTime: 4,
    ingredients: ["شیر عسلی غلیظ", "اسپرسو دابل", "شیر تازه", "یخ"],
    calories: 260,
    tags: ["پرفروش‌ترین", "سرد", "شیرین"],
    sortOrder: 6,
    modifierGroups: coldCoffeeModifiers,
  },
  {
    id: "prod-cold-brew-nitro",
    coffeeShopId: "shop-lamiz",
    categoryId: "cat-cold-coffee",
    name: "Single Origin Cold Brew (24h)",
    nameFa: "کلد برو تخصصی ۲۴ ساعته",
    description: "Cold-steeped for 24 hours to produce a silky, low-acidity coffee with sweet plum and cacao notes.",
    descriptionFa: "عصاره‌گیری سرد ۲۴ ساعته از دانه اتیوپی با اسیدیته بسیار پایین و طعم‌یادهای آلوی سیاه و کاکائو.",
    image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=600&auto=format&fit=crop&q=80",
    basePrice: 105000,
    active: true,
    available: true,
    featured: true,
    popular: false,
    isNew: true,
    preparationTime: 2,
    ingredients: ["قهوه تخصصی اتیوپی", "آب معدنی سرد"],
    calories: 5,
    tags: ["تخصصی", "بدون‌شکر", "خنک"],
    sortOrder: 7,
    modifierGroups: coldCoffeeModifiers,
  },
  {
    id: "prod-iced-caramel-latte",
    coffeeShopId: "shop-lamiz",
    categoryId: "cat-cold-coffee",
    name: "Iced Caramel Macchiato",
    nameFa: "آیس کارامل ماکیاتو",
    description: "Chilled milk over ice with natural vanilla, espresso float, and thick drizzle of house caramel.",
    descriptionFa: "شیر سرد و یخ، سیروپ وانیل دست‌ساز، لایه اسپرسوی غلیظ و سس کارامل لذیذ.",
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&auto=format&fit=crop&q=80",
    basePrice: 115000,
    active: true,
    available: true,
    featured: false,
    popular: true,
    preparationTime: 4,
    ingredients: ["شیر سرد", "اسپرسو", "سس کارامل", "وانیل", "یخ"],
    calories: 230,
    tags: ["سرد", "کاراملی"],
    sortOrder: 8,
    modifierGroups: coldCoffeeModifiers,
  },

  // COLD DRINKS & MOCKTAILS
  {
    id: "prod-matcha-iced-latte",
    coffeeShopId: "shop-lamiz",
    categoryId: "cat-cold-drinks",
    name: "Ceremonial Iced Matcha Latte",
    nameFa: "آیس ماچا لاته تشریفاتی ژاپن",
    description: "Grade-A Uji Kyoto ceremonial matcha whisked fresh with oat milk and pure vanilla syrup over ice.",
    descriptionFa: "پودر ماچای تشریفاتی اصل کیوتو ژاپن، زده‌شده با ویسک بامبو، شیر جو دوسر و طعم‌دهنده طبیعی وانیل.",
    image: "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=600&auto=format&fit=crop&q=80",
    basePrice: 135000,
    active: true,
    available: true,
    featured: true,
    popular: true,
    isNew: true,
    preparationTime: 6,
    ingredients: ["ماچای تشریفاتی اوجی", "شیر گیاهی Oat", "شربت آگاوه یا وانیل"],
    calories: 140,
    tags: ["آنتی‌اکسیدان", "ماچا", "انرژی‌بخش"],
    sortOrder: 9,
    modifierGroups: coldCoffeeModifiers,
  },
  {
    id: "prod-berry-hibiscus-cooler",
    coffeeShopId: "shop-lamiz",
    categoryId: "cat-cold-drinks",
    name: "Wild Berry Hibiscus Mocktail",
    nameFa: "کولر بری و چای ترش دست‌ساز",
    description: "Brewed hibiscus iced tea with crushed raspberries, fresh mint leaves, lime juice, and sparkling soda.",
    descriptionFa: "دمنوش چای ترش سرد با تمشک تازه، نعنای تازه باغی، لیموترش شیرازی و سودای گازدار.",
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80",
    basePrice: 92000,
    active: true,
    available: true,
    featured: false,
    popular: true,
    preparationTime: 5,
    ingredients: ["چای ترش دم‌کشیده", "پوره تمشک و شاه‌توت", "برگ نعنا", "آب گازدار"],
    calories: 85,
    tags: ["طبیعی", "بدون‌کافئین", "شاداب‌کننده"],
    sortOrder: 10,
  },

  // TEA & INFUSIONS
  {
    id: "prod-masala-chai-spiced",
    coffeeShopId: "shop-lamiz",
    categoryId: "cat-tea",
    name: "Royal Spiced Masala Chai",
    nameFa: "چای ماسالا سلطنتی با شیر",
    description: "Traditional Indian black tea simmered with fresh ginger, crushed cardamom, cloves, cinnamon, and whole milk.",
    descriptionFa: "ترکیب اصیل چای سیاه آسام با هل سبز، زنجبیل تازه، دارچین سیلان، میخک و شیر گرم با عسل طبیعی.",
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop&q=80",
    basePrice: 95000,
    active: true,
    available: true,
    featured: false,
    popular: true,
    preparationTime: 7,
    ingredients: ["چای آسام هندوستان", "ادویه‌جات تازه کوبیده‌شده", "شیر کامل", "عسل کوهی"],
    calories: 180,
    tags: ["گرمابخش", "ادویه‌ای"],
    sortOrder: 11,
  },
  {
    id: "prod-persian-black-tea",
    coffeeShopId: "shop-lamiz",
    categoryId: "cat-tea",
    name: "Premium Persian Spring Tea & Saffron",
    nameFa: "چای بهاره لاهیجان با زعفران و هل",
    description: "Finest spring harvest Lahijan black tea infused with dried damask rosebuds, green cardamom, and saffron threads.",
    descriptionFa: "بهترین چای سرگل بهاره دست‌چین گیلان به همراه گل‌سرخ کاشان، هل اعلا و زعفران قائنات در قوری وارمردار.",
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&auto=format&fit=crop&q=80",
    basePrice: 65000,
    active: true,
    available: true,
    featured: false,
    popular: false,
    preparationTime: 5,
    ingredients: ["چای سرگل لاهیجان", "هل", "گل سرخ کاشان", "زعفران"],
    calories: 0,
    tags: ["سنتی", "آرامش‌بخش"],
    sortOrder: 12,
  },

  // CAKES & PASTRIES
  {
    id: "prod-san-sebastian-cheesecake",
    coffeeShopId: "shop-lamiz",
    categoryId: "cat-cake",
    name: "San Sebastian Burnt Cheesecake",
    nameFa: "چیزکیک سن سباستین با سس شکلات بلژیکی",
    description: "Famous creamy Basque-style burnt cheesecake served warm with melted Belgian milk chocolate sauce.",
    descriptionFa: "چیزکیک کرمی کاراملیزه‌شده سبک باسک با بافت ذوب‌شونده در دهان همراه با سس شکلات شیری گرم.",
    image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=600&auto=format&fit=crop&q=80",
    basePrice: 145000,
    compareAtPrice: 160000,
    active: true,
    available: true,
    featured: true,
    popular: true,
    preparationTime: 3,
    ingredients: ["پنیر خامه‌ای اعلا", "خامه طبیعی", "تخم‌مرغ تازه", "شکلات کالیبائو بلژیک"],
    calories: 420,
    tags: ["پرفروش", "لوکس", "شیرینی روز"],
    sortOrder: 13,
  },
  {
    id: "prod-butter-croissant",
    coffeeShopId: "shop-lamiz",
    categoryId: "cat-cake",
    name: "French Pure Butter Croissant",
    nameFa: "کروسان کره فرانسوی تازه پخت",
    description: "Golden flaky croissant baked daily using 100% French cultured butter with incredible crisp layers.",
    descriptionFa: "کروسان برشته و لایه‌ای با کره خالص حیوانی، پخت اول هر روز صبح در فر اختصاصی کافه.",
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop&q=80",
    basePrice: 85000,
    active: true,
    available: true,
    featured: false,
    popular: true,
    preparationTime: 2,
    ingredients: ["آرد فرانسوی T55", "کره حیوانی ۸۲٪", "خمیرمایه تازه"],
    calories: 280,
    tags: ["صبحانه", "کروسان", "تازه"],
    sortOrder: 14,
  },
  {
    id: "prod-carrot-walnut-cake",
    coffeeShopId: "shop-lamiz",
    categoryId: "cat-cake",
    name: "Spiced Carrot Walnut Cake",
    nameFa: "کیک هویج و گردو با کرم‌پنیر",
    description: "Moist spiced carrot cake studded with toasted walnuts and topped with luscious cream cheese frosting.",
    descriptionFa: "کیک هویج لطیف با دارچین تازه، گردوی تست‌شده اعلا و رویه کرم‌پنیر لیمویی دست‌ساز.",
    image: "https://images.unsplash.com/photo-1621303837174-89787a7d4729?w=600&auto=format&fit=crop&q=80",
    basePrice: 110000,
    active: true,
    available: true,
    featured: false,
    popular: true,
    preparationTime: 2,
    ingredients: ["هویج رنده‌شده تازه", "گردو تویسرکان", "دارچین", "فراستینگ پنیر خامه‌ای"],
    calories: 360,
    tags: ["کیک روز", "عصری دلنشین"],
    sortOrder: 15,
  },

  // BREAKFAST & BRUNCH
  {
    id: "prod-avocado-poached-toast",
    coffeeShopId: "shop-lamiz",
    categoryId: "cat-breakfast",
    name: "Avocado Sourdough Toast & Poached Egg",
    nameFa: "تست آووکادو و تخم‌مرغ پوچد روی نان ترش",
    description: "Crushed Hass avocado on toasted artisan sourdough with organic poached eggs, cherry tomatoes, and microgreens.",
    descriptionFa: "پوره آووکادوی هاس تازه روی نان ساوردو خمیرترش برشته، تخم‌مرغ پوچد ارگانیک، پاپریکا دودی و روغن زیتون فرابکر.",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&auto=format&fit=crop&q=80",
    basePrice: 195000,
    active: true,
    available: true,
    featured: true,
    popular: true,
    isNew: true,
    preparationTime: 12,
    ingredients: ["نان خمیرترش ساوردو", "آووکادو تازه هاس", "تخم‌مرغ پوچد", "گوجه گیلاسی", "کنجد بو داده"],
    calories: 380,
    tags: ["سالم", "صبحانه کامل", "پروتئین"],
    sortOrder: 16,
  },
  {
    id: "prod-croissant-turkey-melt",
    coffeeShopId: "shop-lamiz",
    categoryId: "cat-snacks",
    name: "Smoked Turkey & Gouda Melt Croissant",
    nameFa: "ساندویچ کروسان گرم بوقلمون دودی و پنیر گودا",
    description: "Warm butter croissant loaded with smoked turkey breast, melted mature gouda cheese, and dijon aioli.",
    descriptionFa: "کروسان گرم با ژامبون بوقلمون دودی ۹۰٪، پنیر گودای آب‌شده، گوجه فرنگی خشک، ریحان ایتالیایی و سس سس خردل دیژون.",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?w=600&auto=format&fit=crop&q=80",
    basePrice: 175000,
    active: true,
    available: true,
    featured: false,
    popular: true,
    preparationTime: 8,
    ingredients: ["کروسان کره‌ای", "سینه بوقلمون دودی", "پنیر گودا هلندی", "سس خردل ملایم"],
    calories: 450,
    tags: ["گرم", "میان‌وعده", "سیرکننده"],
    sortOrder: 17,
  },
  {
    id: "prod-waffle-belgian-berries",
    coffeeShopId: "shop-lamiz",
    categoryId: "cat-dessert",
    name: "Crispy Belgian Waffle with Berries & Gelato",
    nameFa: "وافل بلژیکی با توت‌فرنگی تازه و جلاتو وانیل",
    description: "Freshly made pearl-sugar waffle served with fresh strawberries, dark chocolate ganache, and Madagascar vanilla gelato.",
    descriptionFa: "وافل داغ و ترد بلژیکی با توت‌فرنگی تازه، گاناش شکلات تلخ بلژیکی، یک اسکوپ جلاتو وانیل و پودر قند.",
    image: "https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=600&auto=format&fit=crop&q=80",
    basePrice: 165000,
    compareAtPrice: 180000,
    active: true,
    available: true,
    featured: true,
    popular: true,
    preparationTime: 10,
    ingredients: ["خمیر وافل بلژیکی", "توت‌فرنگی تازه", "جلاتو وانیل دست‌ساز", "شکلات تلخ ذوب‌شده"],
    calories: 510,
    tags: ["دسر ویژه", "شیرین"],
    sortOrder: 18,
  },
];

export const initialCoupons: Coupon[] = [
  {
    id: "coupon-welcome",
    coffeeShopId: "shop-lamiz",
    code: "WELCOME20",
    discountType: "percentage",
    discountValue: 20,
    minOrderAmount: 100000,
    maxDiscountAmount: 50000,
    expiryDate: "2026-12-30",
    usageLimit: 500,
    usedCount: 42,
    active: true,
    description: "۲۰٪ تخفیف اولین سفارش کافه پلاس برای سفارش‌های بالای ۱۰۰ هزار تومان",
  },
  {
    id: "coupon-lamiz-fixed",
    coffeeShopId: "shop-lamiz",
    code: "LAMIZ30",
    discountType: "fixed",
    discountValue: 30000,
    minOrderAmount: 150000,
    maxDiscountAmount: 30000,
    expiryDate: "2026-12-31",
    usageLimit: 200,
    usedCount: 18,
    active: true,
    description: "۳۰,۰۰۰ تومان تخفیف نقدی برای سفارش‌های بالای ۱۵۰ هزار تومان",
  },
  {
    id: "coupon-coffeelover",
    coffeeShopId: "shop-lamiz",
    code: "COFFEELOVER",
    discountType: "percentage",
    discountValue: 15,
    minOrderAmount: 80000,
    maxDiscountAmount: 40000,
    expiryDate: "2026-12-31",
    usageLimit: 1000,
    usedCount: 110,
    active: true,
    description: "۱۵٪ تخفیف همراهان همیشگی کافه لمیز",
  },
];
